[project]
name = "ask-your-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.0",
    "langfuse>=4.13.0",
    "openai>=2.44.0",
    "python-dotenv>=1.2.2",
    "sqlglot>=30.12.0",
    "uvicorn>=0.50.0",
]
